// Mocks generated by Mockito 5.4.4 from annotations
// in evoleen_fhir_events/test/message_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i4;

import 'package:azstore/src/azstore_core.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AzureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzureStorage extends _i1.Mock implements _i3.AzureStorage {
  MockAzureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set config(Map<String, String>? _config) => super.noSuchMethod(
        Invocation.setter(
          #config,
          _config,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set accountKey(_i4.Uint8List? _accountKey) => super.noSuchMethod(
        Invocation.setter(
          #accountKey,
          _accountKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Uri uri({
    String? path = r'/',
    Map<String, String>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uri,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #uri,
            [],
            {
              #path: path,
              #queryParameters: queryParameters,
            },
          ),
        ),
      ) as Uri);

  @override
  _i5.Future<void> createContainer(
    String? name, {
    int? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createContainer,
          [name],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteContainer(
    String? name, {
    int? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContainer,
          [name],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.StreamedResponse> getBlob(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getBlob,
          [path],
        ),
        returnValue:
            _i5.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #getBlob,
            [path],
          ),
        )),
      ) as _i5.Future<_i2.StreamedResponse>);

  @override
  _i5.Future<void> putBlob(
    String? path, {
    String? body,
    _i4.Uint8List? bodyBytes,
    required String? contentType,
    _i3.BlobType? type = _i3.BlobType.blockBlob,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putBlob,
          [path],
          {
            #body: body,
            #bodyBytes: bodyBytes,
            #contentType: contentType,
            #type: type,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBlob(
    String? path, {
    _i3.BlobType? type = _i3.BlobType.blockBlob,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBlob,
          [path],
          {#type: type},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> appendBlock(
    String? path, {
    String? body,
    _i4.Uint8List? bodyBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendBlock,
          [path],
          {
            #body: body,
            #bodyBytes: bodyBytes,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createTable(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #createTable,
          [tableName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTable(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #deleteTable,
          [tableName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String?>> getTables() => (super.noSuchMethod(
        Invocation.method(
          #getTables,
          [],
        ),
        returnValue: _i5.Future<List<String?>>.value(<String?>[]),
      ) as _i5.Future<List<String?>>);

  @override
  _i5.Future<void> upsertTableRow({
    required String? tableName,
    required String? partitionKey,
    required String? rowKey,
    String? body,
    Map<String, dynamic>? bodyMap,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertTableRow,
          [],
          {
            #tableName: tableName,
            #partitionKey: partitionKey,
            #rowKey: rowKey,
            #body: body,
            #bodyMap: bodyMap,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> putTableRow({
    String? tableName,
    String? partitionKey,
    String? rowKey,
    String? body,
    Map<String, dynamic>? bodyMap,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putTableRow,
          [],
          {
            #tableName: tableName,
            #partitionKey: partitionKey,
            #rowKey: rowKey,
            #body: body,
            #bodyMap: bodyMap,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getTableRow({
    String? tableName,
    String? partitionKey,
    String? rowKey,
    List<String>? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTableRow,
          [],
          {
            #tableName: tableName,
            #partitionKey: partitionKey,
            #rowKey: rowKey,
            #fields: fields,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTableRow,
            [],
            {
              #tableName: tableName,
              #partitionKey: partitionKey,
              #rowKey: rowKey,
              #fields: fields,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<dynamic>> filterTableRows({
    required String? tableName,
    required String? filter,
    int? top = 20,
    List<String>? fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterTableRows,
          [],
          {
            #tableName: tableName,
            #filter: filter,
            #top: top,
            #fields: fields,
          },
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<void> deleteTableRow({
    required String? tableName,
    required String? partitionKey,
    required String? rowKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTableRow,
          [],
          {
            #tableName: tableName,
            #partitionKey: partitionKey,
            #rowKey: rowKey,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createQueue(String? qName) => (super.noSuchMethod(
        Invocation.method(
          #createQueue,
          [qName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> getQData(String? qName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQData,
          [qName],
        ),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> deleteQueue(String? qName) => (super.noSuchMethod(
        Invocation.method(
          #deleteQueue,
          [qName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getQList() => (super.noSuchMethod(
        Invocation.method(
          #getQList,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> putQMessage({
    required String? qName,
    int? messagettl = 604800,
    int? vtimeout = 0,
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQMessage,
          [],
          {
            #qName: qName,
            #messagettl: messagettl,
            #vtimeout: vtimeout,
            #message: message,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AzureQMessage>> getQmessages({
    required String? qName,
    int? numOfmessages = 20,
    int? visibilitytimeout,
    int? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQmessages,
          [],
          {
            #qName: qName,
            #numOfmessages: numOfmessages,
            #visibilitytimeout: visibilitytimeout,
            #timeout: timeout,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.AzureQMessage>>.value(<_i3.AzureQMessage>[]),
      ) as _i5.Future<List<_i3.AzureQMessage>>);

  @override
  _i5.Future<List<_i3.AzureQMessage>> peekQmessages({
    required String? qName,
    int? numofmessages = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #peekQmessages,
          [],
          {
            #qName: qName,
            #numofmessages: numofmessages,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.AzureQMessage>>.value(<_i3.AzureQMessage>[]),
      ) as _i5.Future<List<_i3.AzureQMessage>>);

  @override
  _i5.Future<void> delQmessage({
    required String? qName,
    required String? messageId,
    required String? popReceipt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delQmessage,
          [],
          {
            #qName: qName,
            #messageId: messageId,
            #popReceipt: popReceipt,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateQmessage({
    required String? qName,
    required String? messageId,
    Duration? vTimeout,
    required String? message,
    required String? popReceipt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQmessage,
          [],
          {
            #qName: qName,
            #messageId: messageId,
            #vTimeout: vTimeout,
            #message: message,
            #popReceipt: popReceipt,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearQmessages(String? qName) => (super.noSuchMethod(
        Invocation.method(
          #clearQmessages,
          [qName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
