name: azure_fhir_event_processor
description: Process FHIR events emitted by Azure Health Data Services using
  Dart queue workers.
version: 1.0.1
repository: https://github.com/evoleen/azure_fhir_event_processor

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  azstore: ^1.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  http: ^0.13.0
  json_serializable: ^6.8.0
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.24.0
